baseURL = "https://florisdenhengst.github.io"
languageCode = "en-us"
title = "Floris den Hengst's Homepage"
googleAnalytics = ""
disqusShortname = ""
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

theme = "metis"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4


[params]
    description = "A website built through Hugo."
    footer = [
        "[<img src='https://simpleicons.org/icons/rss.svg'>](/index.xml)",
        "[<img src='https://simpleicons.org/icons/github.svg'>](https://github.com/florisdenhengst/)",
        "[<img src='https://simpleicons.org/icons/linkedin.svg'>](https://www.linkedin.com/in/floris-den-hengst-06ab7534/)",
        "[<img src='/static/imgs/gscholar.png'>](https://scholar.google.nl/citations?user=8I8iSHkAAAAJ)",
        "| Created with [Hugo](https://gohugo.io) and [Metis](https://florisdenhengst.github.io/metis-example/) theme | &copy; [Floris den Hengst](https://florisdenhengst.github.io) 2018 -- 2019", 
        ]
